### ISSUE TITLE
How to install dependencies?

### ISSUE THREAD

**Issue by Terahertz0** [yaoyao-liu/class-incremental-learning#14]
How to install the [dependencies](https://yyliu.net/files/mnemonics_packages.txt) required for the [mnemonics training](https://github.com/yaoyao-liu/class-incremental-learning/tree/main/mnemonics-training) repository?

**Comment by yaoyao-liu** [comment]
Thanks for your interest in our work.

To run our project, we recommend you install python 3.6 and PyTorch 0.4.0 with Anaconda.
You may download Anaconda and read the installation instruction on their official website: <https://www.anaconda.com/download/>.

Then install PyTorch:
```
conda create --name mnemonics-training python=3.6
conda activate mnemonics-training
conda install pytorch=0.4.0
conda install torchvision -c pytorch
```
Install other dependencies:
```
pip install tqdm tensorboardX Pillow==6.2.2 scipy
```
If you still lack some python packages, you may install them using `pip install xxx`.
If you have further questions, please let me know.

Best,
Yaoyao

**Comment by Terahertz0** [comment]
Can this project work on windows?

**Comment by yaoyao-liu** [comment]
I think it is possible to run it using Windows. But I have never tested it. I run it using `Debian 8.3.0-6`.
I recommend you run this project using a Debian or Ubuntu workstation.

**Comment by Terahertz0** [comment]
My application currently constrains me to using Windows, I will close this issue and reopen it whenever needed, thanks greatly for your support.
