### ISSUE TITLE
Code for PODNet-CNN + AANets

### ISSUE THREAD

**Issue by JosephKJ** [yaoyao-liu/class-incremental-learning#23]
Hi @yaoyao-liu, 

Thank you for your amazing works! 

I was trying to improve upon your work, and would like to replicate PODNet-CNN + AANets, because it has the best performance when compared to other methods. Hence, it qualifies to be called as AANets results for comparison. 

It would be very kind of you if you could provide code for PODNet-CNN + AANets. It is okay even if it is not polished.

Thanks,
Joseph

**Comment by yaoyao-liu** [comment]
Hi @JosephKJ,

Thanks for your interest in our work.
I will send you the implementation of PODNet + AANets in several days.

Best,
Yaoyao

**Comment by yaoyao-liu** [comment]
Hi @JosephKJ,

This is the code for POD+AANets: https://drive.google.com/file/d/1ngKvJNWUxTnl-KiQk9pDTJD4scPqKRaV/view?usp=sharing


As I haven't cleaned up the code, it would be a bit messy. I am sorry for that.
If you have any further questions, feel free to email me or add comments to this issue.

Best,
Yaoyao

**Comment by JosephKJ** [comment]
Thank you very much, @yaoyao-liu! I have requested access to the drive folder, kindly allow when you get a chance. 

Thanks again!
Joseph

**Comment by JosephKJ** [comment]
Just received. Thank you very much :)

**Comment by daihu-ye** [comment]
Hi,i also need the code. I have requested access to the drive folder,please allow when you are free

**Comment by yaoyao-liu** [comment]
@daihu-ye 

I have allowed it.

**Comment by bellos1203** [comment]
Hello, I also request access to the code for my experiments. Please allow me when you are free.
Thanks a lot!

**Comment by yaoyao-liu** [comment]
Hi @bellos1203,

I have allowed it. If you have further questions, feel free to contact me.
