### ISSUE TITLE
A request 

### ISSUE THREAD

**Issue by JosephKJ** [yaoyao-liu/class-incremental-learning#25]
Hello @yaoyao-liu,

If you have the numbers for each datapoint to redraw Figure S2 in AAN paper (all the graphs with accuracy at each step), can you share that across?

This would help to recreate the graph without having  to rerun all the baselines.

It would be very kind of you if you could share it along. 

Thanks,
Joseph

**Comment by yaoyao-liu** [comment]
Thanks for your interest in our work.

You may find the accuracy for each phase here: <https://docs.google.com/spreadsheets/d/1KFsWnVGEig3f-O-zn9t4vi30ntOtUUAwrY8QhSIFCzE/edit?usp=sharing>

**Comment by JosephKJ** [comment]
Thank you very much @yaoyao-liu. You are very helpful. 

I have requested access, kindly allow when you get a chance.
