### ISSUE TITLE
Paper uses dynamic budget, but repository recommends fixed?

### ISSUE THREAD

**Issue by ashok-arjun** [yaoyao-liu/class-incremental-learning#30]
Hi,

The paper uses a dynamic budget of 20 exemplars per class in training the models associated with every result reported.

However, the bash commands that you provide do not contain the flag `--dynamic_budget` at all.

Does that mean the code uses a fixed budget? In that case, what does the flag indicate?

Thanks!

**Comment by yaoyao-liu** [comment]
Yes. The memory budget is fixed if you run the code without the flag `--dynamic_budget`.

If you need to run the experiments with the setting "20 exemplars per class", you must add `--dynamic_budget` to your command.

**Comment by ashok-arjun** [comment]
Got it, thank you @yaoyao-liu !
