### ISSUE TITLE
Question about exemplar selection code

### ISSUE THREAD

**Issue by ashok-arjun** [yaoyao-liu/class-incremental-learning#31]
Hi @yaoyao-liu ,

I understand the code for herding selection and how the `alpha_dr_herding` is populated. 

But I don't understand how the class-means are calculated.

https://github.com/yaoyao-liu/class-incremental-learning/blob/61118593f331c8ee6f7eaa76ddb8ff75ece14b4d/adaptive-aggregation-networks/trainer/base_trainer.py#L939

What does the line `(np.dot(D,alph)+np.dot(D2,alph))/2` do? 
Why can it not be just np.dot(D, alph)?

**Comment by yaoyao-liu** [comment]
Thanks for your interest in our work.
`D` and `D2` are the features for the original and flipped exemplars, respectively.
The operation follows [LUCIR](https://github.com/hshustc/CVPR19_Incremental_Learning):

https://github.com/hshustc/CVPR19_Incremental_Learning/blob/e5a90aed7640f3b00e5b1a8dfb5376c1628bfe6a/cifar100-class-incremental/class_incremental_cosine_cifar100.py#L420-L456

**Comment by ashok-arjun** [comment]
Got it, thank you @yaoyao-liu.
