### ISSUE TITLE
Code for T-SNE in the mnemonics paper

### ISSUE THREAD

**Issue by ashok-arjun** [yaoyao-liu/class-incremental-learning#36]
Hi @yaoyao-liu, 

Thank you for the perfect codebase to experiment upon, and two very interesting papers.

I was captivated by **Figure 1** of your [mnemonics paper](https://arxiv.org/pdf/2002.10211.pdf) where you have plotted the data and highlighted the exemplars.

Can you please lend me your code that generated it (how you get such well spaced clusters, as well as how you highlight the exemplars)? It would be of great use to my work.

Thank you very much.

**Comment by yaoyao-liu** [comment]
Hi @ashok-arjun,

Thanks for your interest in our work.

I use [this script](https://drive.google.com/file/d/1TTj4FmCD6dEHkdY2uRKQgL2Ow1u7iLbV/view?usp=sharing) to create the teaser figure in my paper. I am sorry I didn't clean the code in this script. Maybe you need to revise the code to make it work in your settings. 

Please consider citing my work if the code is helpful. If you have any questions, feel free to ask :)

Have a nice day.

Best,
Yaoyao

**Comment by ashok-arjun** [comment]
Thank you for the link @yaoyao-liu. Can you kindly grant me access to it? My email is `arjun.ashok.psg@gmail.com`.

Thank you very much again, for the help!

**Comment by yaoyao-liu** [comment]
Hi @ashok-arjun,

I have shared it with you via Google Drive. I think you will get an email about it.
Have a nice day.

Best,
Yaoyao

**Comment by ashok-arjun** [comment]
I have got the link. Thank you very much for the timely help, @yaoyao-liu.
