### ISSUE TITLE
question about `modified_linear.py`

### ISSUE THREAD

**Issue by letme-hj** [yaoyao-liu/class-incremental-learning#38]
Hello,
I have a question regarding what the module `modified_linear.py` does.

Isn't the cosine linear layer a component for LUCIR? 
I thought the layer was for cosine normalization and therefore should only be used for LUCIR, but your code doesn't seem to choose the resnet model dependent on the method (LUCIR/ICARL) so I wonder if I'm missing something.

I'm sorry in advance that I might have totally misunderstood the concept and might be bothering you.

Thank you!!

**Comment by yaoyao-liu** [comment]
Hi @letme-hj,

Your understanding is correct. The "iCaRL" in this project can be regarded as "iCaRL"+"cosine classifier".
if you need to remove the cosine normalization on the classifier weights, you may revise the following lines:
https://github.com/yaoyao-liu/class-incremental-learning/blob/7604cf40844e88cf42e1e80eca725e2f33468e16/adaptive-aggregation-networks/models/modified_linear.py#L35-L40

If you have further questions, please feel free to add more comments to this issue or create a new issue.

Have a nice day.

Best,
Yaoyao

**Comment by letme-hj** [comment]
Thank you so much for making it clear for me!
