### ISSUE TITLE
Inquiries about the comparison between mnemonics and baseline

### ISSUE THREAD

**Issue by tingxueronghua** [yaoyao-liu/class-incremental-learning#41]
Hi, I am reading the code of mnemonics-training, and want to verify the effectiveness of the algorithm, which is related to dataset distillation. However, when I read the code, I noticed that the network implemented [here](https://github.com/yaoyao-liu/class-incremental-learning/blob/6fead2f6546a863a17b74234001d0393330ac8fc/mnemonics-training/1_train/trainer/mnemonics.py#L106) in mnemonics.py is different from [that](https://github.com/yaoyao-liu/class-incremental-learning/blob/6fead2f6546a863a17b74234001d0393330ac8fc/mnemonics-training/1_train/trainer/baseline.py#L106) in baseline.py
I think it could be more reasonable to change the "self.network_mtl" to "self.network" when comparing baseline and mnemonics. I want to inquire why mnemonics uses network_mtl, while baseline uses a different model. 

Another inquiry is about the "fusion_mode". I have seen some issues discussing about it, but I have not figured out how this option influences the code. What's this option designed for?

**Comment by yaoyao-liu** [comment]
Hi @tingxueronghua,

Thanks for your interest in our work!

For your Q1: the mnemonics exemplars and the mtl networks are both our designs. Using these two components together achieves the best performance. 

For your Q2: the `fusion_mode` is an interface for a future project. It is not used in this project, and you may directly ignore it. 

If you have any further questions, please do not hesitate to contact me!

**Comment by tingxueronghua** [comment]
Thanks! Your answer is clear. I have no other questions!
