### ISSUE TITLE
PODNET-AAN Related experiment running issue!

### ISSUE THREAD

**Issue by castlezone** [yaoyao-liu/class-incremental-learning#43]
[](url)One more thing please, 
I am trying to run the experiment of POD-AANets, please verify that this is the right way to run the experiment? Because I am getting error and not able to find out the way to execute it successfully. I have installed all the required libraries as well. Thank you!

I have cloned this repository:  https://github.com/yaoyao-liu/POD-AANets

Installed all the required libraries which you mentioned from: https://github.com/arthurdouillard/incremental_learning.pytorch

I have attached the screenshot the error which is coming out, while I am running it on NVIDEA T4. Like when I execute this command "python run_exp.py" then this data loader trace back type of error is popping out. 

Thank you once again and looking [forward.]

**Comment by yaoyao-liu** [comment]
Thanks for your interest in our work.

It seems you didn't put the dataset in the correct directory. 
You also need to prepare for the dataset following [PODNet](https://github.com/arthurdouillard/incremental_learning.pytorch).

If you have any questions, please do not hesitate to contact me.

**Comment by castlezone** [comment]
I am following this path:  "POD-AANets/main/data/imagenet"
here I have pasted my imagenet subset dataset subfolders train, val, samples. 
Please guide me if this is the correct path and it would be better if you mention the command where the path of the dataset is written. 
Because I am following everything described and mentioned by you and the other author.  Thank you for your support.

**Comment by castlezone** [comment]
Finally, I have been able to execute the code. I just renamed the file names according to the paths. So, finally, after setting my dataset, I am successfully able to run it.

**Comment by yaoyao-liu** [comment]
My apologies for the late reply. It seems your issue has been solved. If you have any further questions, please do not hesitate to contact me.
