### ISSUE TITLE
What does the flag `--fusion_mode` represent?

### ISSUE THREAD

**Issue by michael-qiyao** [yaoyao-liu/class-incremental-learning#7]
Hi,
    I notice that the target model in the squential class-incremental training is set to network_mtl. Regarding your implementation for constructing an "mtl" network, it seems every weight of convolution kernels is freezed and multiplied by a learnable mask (initialized as 1). My question is why the network architecture is implemented in this way?

Thanks in adavance!
Michael

**Comment by yaoyao-liu** [comment]
Thanks for your interest in our work.

We deploy weight transfer operations to train the weight scaling and shifting parameters. The aim is to preserve the structural knowledge of the previous model. Please kindly refer to the ***Supplementary materials, Section B*** for details: [arXiv link](https://arxiv.org/pdf/2002.10211.pdf).
